version: "2.1"

defaults:
  only-tag-filter: &filter-only-tagged
    filters:
      branches:
        ignore: /.*/
      tags:
        only: /.*/
  only-master-filter: &filter-only-master
    filters:
      branches:
        only: /master/
      tags:
        ignore: /.*/

executors:
  python-3:
    docker:
      - image: circleci/python:3.7
    working_directory: ~/source

workflows:
  version: "2"
  build-workflow:  # PRs and merges into master
    jobs:
      - create-workspace
      - test:
          requires:
            - create-workspace

jobs:
  create-workspace:  # create environment, install requirements
    executor: python-3
    steps:
      - checkout
      - attach_workspace:
          at: ~/workspace
      - restore_cache:  # if we have a cache, use it
          keys:
            - environment-cache-py3-{{ checksum "setup.py" }}
            - environment-cache-py3-
      - run:
          name: Install depdendencies
          command: |
            python -mvenv ~/workspace/env
            . ~/workspace/env/bin/activate
            pip install -e '.[dev]'
            pip install 'nose==1.3.7'
      - save_cache:
          paths:
            - ~/workspace/env
          key: environment-cache-py3-{{ checksum "setup.py" }}
      - persist_to_workspace:
          root: ~/workspace
          paths:
            - ./env

  test:  # run tests with coverage enabled
    executor: python-3
    steps:
      - checkout
      - attach_workspace:
          at: ~/workspace
      - run:
          name: Run tests
          command: |
            . ~/workspace/env/bin/activate
            mkdir -p build/reports
            nosetests --with-coverage --cover-package klempner \
              --cover-xml --cover-xml-file build/reports/coverage.xml \
              --with-xunit --xunit-file build/reports/junit.xml
            cp .coverage ~/workspace/coverage-py3
      - store_test_results:
          path: build/reports
      - persist_to_workspace:
          root: ~/workspace
          paths:
            - coverage-py3
      - store_artifacts:
          path: build/reports
          destination: build-reports
